### ISSUE TITLE
Migration to version 15.0

### ISSUE THREAD

**Issue by oihane** [avanzosc/hr-addons#126]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

# Modules to migrate

- [ ] hr_applicant_show_field
- [ ] hr_employee_departure_reason
- [ ] hr_employee_resume_line
- [ ] hr_employee_skills_menu
- [ ] hr_expense_event_commute
- [ ] hr_expense_from_analytic
- [ ] hr_hide_info
- [ ] hr_skills_hide_info
- [ ] hr_timesheet_schedule

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list
