### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by oihane** [avanzosc/hr-addons#21]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] calendar_holiday
- [ ] calendar_holiday_project_task
- [ ] calendar_holiday_project_timesheet
- [ ] hr_attendance_control
- [ ] hr_attendance_from_kanban
- [ ] hr_attendance_report
- [ ] hr_calendar_zone
- [ ] hr_contract_extra
- [ ] hr_contract_history
- [ ] hr_contract_stages
- [ ] hr_employee_associated_picking
- [ ] hr_employee_catch_partner
- [ ] hr_employee_deactivate
- [ ] hr_recruitment_skill
- [ ] hr_recruitment_zone
- [ ] hr_timesheet_invoice_by_partner
