### ISSUE TITLE
Migration to version 12.0

### ISSUE THREAD

**Issue by oihane** [avanzosc/hr-addons#50]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

# Modules to migrate

- [ ] hr_employee_analytic_entries_shortcut
- [ ] hr_employee_associated_picking
- [ ] hr_employee_catch_partner
- [ ] hr_employee_product
- [ ] hr_timesheet_characterization
- [ ] hr_timesheet_kind
